export const screenSizes = {
  sm: 640,
  md: 768,
  lg: 1024,
  xl: 1280,
  "2xl": 1536,
};

export const courses = [
  {
    id: 1,
    title: "ReactJS",
    type: "frontend",
    form: "offline",
    price: 4500000,
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/react-course.svg",
  },
  {
    id: 2,
    title: "NodeJS",
    type: "backend",
    form: "offline",
    price: 4500000,
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/nodejs-course.svg",
  },
  {
    id: 3,
    title: "PHP",
    type: "backend",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/php-course.svg",
  },
  {
    id: 4,
    title: "Flutter",
    type: "mobile",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/flutter-course.svg",
  },
  {
    id: 5,
    title: "QC",
    type: "qc",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/qc-course.svg",
  },
  {
    id: 6,
    title: "Unity",
    type: "game",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/unity-course.svg",
  },
  {
    id: 7,
    title: "Blockchain",
    type: "blockchain",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/blockchain-course.svg",
  },
  {
    id: 8,
    title: "QC",
    type: "qc",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/qc-course.svg",
  },
  {
    id: 9,
    title: "IOT",
    type: "iot",
    price: 4500000,
    form: "offline",
    teacher: "Jane Cooper",
    avatar: "./src/images/courses/teacher-1.svg",
    thumbnail: "./src/images/courses/iot-course.svg",
  },
];
